//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStudentAutomation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcStudentAutomation.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acil.
        /// </summary>
        public static string Acil {
            get {
                return ResourceManager.GetString("Acil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string Adi {
            get {
                return ResourceManager.GetString("Adi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aile.
        /// </summary>
        public static string Aile {
            get {
                return ResourceManager.GetString("Aile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviteler.
        /// </summary>
        public static string Aktiviteler {
            get {
                return ResourceManager.GetString("Aktiviteler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana.
        /// </summary>
        public static string Ana {
            get {
                return ResourceManager.GetString("Ana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfaya Geri Dön.
        /// </summary>
        public static string AnasayfaDon {
            get {
                return ResourceManager.GetString("AnasayfaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara....
        /// </summary>
        public static string Arama {
            get {
                return ResourceManager.GetString("Arama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistan.
        /// </summary>
        public static string Asistan {
            get {
                return ResourceManager.GetString("Asistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string Ayarlar {
            get {
                return ResourceManager.GetString("Ayarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık.
        /// </summary>
        public static string Aylik {
            get {
                return ResourceManager.GetString("Aylik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantılar.
        /// </summary>
        public static string Baglantilar {
            get {
                return ResourceManager.GetString("Baglantilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen Paneli.
        /// </summary>
        public static string Baslik {
            get {
                return ResourceManager.GetString("Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekleyen Görevin Var.
        /// </summary>
        public static string BekleyenGorev {
            get {
                return ResourceManager.GetString("BekleyenGorev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string BeniHatirla {
            get {
                return ResourceManager.GetString("BeniHatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim Paneli.
        /// </summary>
        public static string BildirimPaneli {
            get {
                return ResourceManager.GetString("BildirimPaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bileşenler.
        /// </summary>
        public static string Bilesenler {
            get {
                return ResourceManager.GetString("Bilesenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Adı.
        /// </summary>
        public static string Bolum {
            get {
                return ResourceManager.GetString("Bolum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Adı.
        /// </summary>
        public static string BolumAd {
            get {
                return ResourceManager.GetString("BolumAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butonlar.
        /// </summary>
        public static string Butonlar {
            get {
                return ResourceManager.GetString("Butonlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün Dersler.
        /// </summary>
        public static string ButunDers {
            get {
                return ResourceManager.GetString("ButunDers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkart.
        /// </summary>
        public static string Cikart {
            get {
                return ResourceManager.GetString("Cikart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string CikisYap {
            get {
                return ResourceManager.GetString("CikisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çöp.
        /// </summary>
        public static string Cop {
            get {
                return ResourceManager.GetString("Cop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çöp Kutusu.
        /// </summary>
        public static string CopKutu {
            get {
                return ResourceManager.GetString("CopKutu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dakika Önce.
        /// </summary>
        public static string DakikaOnce {
            get {
                return ResourceManager.GetString("DakikaOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Adı.
        /// </summary>
        public static string DersAd {
            get {
                return ResourceManager.GetString("DersAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Seçimi.
        /// </summary>
        public static string DersSecim {
            get {
                return ResourceManager.GetString("DersSecim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam Etmekte.
        /// </summary>
        public static string DevamEtmekte {
            get {
                return ResourceManager.GetString("DevamEtmekte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string DogumTarih {
            get {
                return ResourceManager.GetString("DogumTarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Yeri.
        /// </summary>
        public static string DogumYer {
            get {
                return ResourceManager.GetString("DogumYer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string Durum {
            get {
                return ResourceManager.GetString("Durum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Duzenle {
            get {
                return ResourceManager.GetString("Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenleme Ekranı.
        /// </summary>
        public static string Duzenleme {
            get {
                return ResourceManager.GetString("Duzenleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski Projeler.
        /// </summary>
        public static string EskiProjeler {
            get {
                return ResourceManager.GetString("EskiProjeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Hakları Saklıdır | Ali Bulut Tarafından Dizayn Edildi.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forumlar.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri.
        /// </summary>
        public static string Galeri {
            get {
                return ResourceManager.GetString("Galeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geç Kaldı.
        /// </summary>
        public static string Gec {
            get {
                return ResourceManager.GetString("Gec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen.
        /// </summary>
        public static string Gelen {
            get {
                return ResourceManager.GetString("Gelen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Kutusu.
        /// </summary>
        public static string GelenKutusu {
            get {
                return ResourceManager.GetString("GelenKutusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen.
        /// </summary>
        public static string Gonderilen {
            get {
                return ResourceManager.GetString("Gonderilen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik.
        /// </summary>
        public static string Grafik {
            get {
                return ResourceManager.GetString("Grafik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün İçinde.
        /// </summary>
        public static string GunIcınde {
            get {
                return ResourceManager.GetString("GunIcınde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük.
        /// </summary>
        public static string Gunluk {
            get {
                return ResourceManager.GetString("Gunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata Sayfası.
        /// </summary>
        public static string HataSayfasi {
            get {
                return ResourceManager.GetString("HataSayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabın Yok Mu? Kayıt Ol.
        /// </summary>
        public static string HesapKayitOl {
            get {
                return ResourceManager.GetString("HesapKayitOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iconlar.
        /// </summary>
        public static string Iconlar {
            get {
                return ResourceManager.GetString("Iconlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlerleme.
        /// </summary>
        public static string Ilerleme {
            get {
                return ResourceManager.GetString("Ilerleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndir.
        /// </summary>
        public static string Indır {
            get {
                return ResourceManager.GetString("Indır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş.
        /// </summary>
        public static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstatistikler.
        /// </summary>
        public static string Istatistikler {
            get {
                return ResourceManager.GetString("Istatistikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstemciler.
        /// </summary>
        public static string Istemciler {
            get {
                return ResourceManager.GetString("Istemciler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string KayıtOl {
            get {
                return ResourceManager.GetString("KayıtOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Paneli.
        /// </summary>
        public static string KontrolPanel {
            get {
                return ResourceManager.GetString("KontrolPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string KullaniciAdi {
            get {
                return ResourceManager.GetString("KullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Gönderildi.
        /// </summary>
        public static string MesajGitti {
            get {
                return ResourceManager.GetString("MesajGitti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müdür.
        /// </summary>
        public static string Mudur {
            get {
                return ResourceManager.GetString("Mudur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Sayısı.
        /// </summary>
        public static string OgrenciSayisi {
            get {
                return ResourceManager.GetString("OgrenciSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmen.
        /// </summary>
        public static string Öğretmen {
            get {
                return ResourceManager.GetString("Öğretmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olarak Çıkart.
        /// </summary>
        public static string OlarakCikart {
            get {
                return ResourceManager.GetString("OlarakCikart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önemli.
        /// </summary>
        public static string Onemli {
            get {
                return ResourceManager.GetString("Onemli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patron.
        /// </summary>
        public static string Patron {
            get {
                return ResourceManager.GetString("Patron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeler.
        /// </summary>
        public static string Projeler {
            get {
                return ResourceManager.GetString("Projeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promosyonlar.
        /// </summary>
        public static string Promosyon {
            get {
                return ResourceManager.GetString("Promosyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor.
        /// </summary>
        public static string Rapor {
            get {
                return ResourceManager.GetString("Rapor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim.
        /// </summary>
        public static string Resim {
            get {
                return ResourceManager.GetString("Resim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saat Önce.
        /// </summary>
        public static string SaatOnce {
            get {
                return ResourceManager.GetString("SaatOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string Sayfalar {
            get {
                return ResourceManager.GetString("Sayfalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş Dersler.
        /// </summary>
        public static string SeciliDers {
            get {
                return ResourceManager.GetString("SeciliDers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        public static string SifreTekrar {
            get {
                return ResourceManager.GetString("SifreTekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        public static string SifreUnuttum {
            get {
                return ResourceManager.GetString("SifreUnuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal.
        /// </summary>
        public static string Sosyal {
            get {
                return ResourceManager.GetString("Sosyal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        public static string Soyad {
            get {
                return ResourceManager.GetString("Soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string Spam {
            get {
                return ResourceManager.GetString("Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.S.S..
        /// </summary>
        public static string sss {
            get {
                return ResourceManager.GetString("sss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoklar Tükendi.
        /// </summary>
        public static string Stok {
            get {
                return ResourceManager.GetString("Stok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu Çöktü.
        /// </summary>
        public static string SunucuCoktu {
            get {
                return ResourceManager.GetString("SunucuCoktu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu Yeniden Başlatıldı.
        /// </summary>
        public static string SunucuYeniden {
            get {
                return ResourceManager.GetString("SunucuYeniden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablolar.
        /// </summary>
        public static string Tablolar {
            get {
                return ResourceManager.GetString("Tablolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak.
        /// </summary>
        public static string Taslak {
            get {
                return ResourceManager.GetString("Taslak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tc Kimlik No.
        /// </summary>
        public static string TcNo {
            get {
                return ResourceManager.GetString("TcNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipografya.
        /// </summary>
        public static string Tipografya {
            get {
                return ResourceManager.GetString("Tipografya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Bildirimleri Gör.
        /// </summary>
        public static string TumBildirimler {
            get {
                return ResourceManager.GetString("TumBildirimler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Yapılacak Görevleri Gör.
        /// </summary>
        public static string TumGorevler {
            get {
                return ResourceManager.GetString("TumGorevler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Mesajları Gör.
        /// </summary>
        public static string TumMesajlar {
            get {
                return ResourceManager.GetString("TumMesajlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string Tutar {
            get {
                return ResourceManager.GetString("Tutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string Urun {
            get {
                return ResourceManager.GetString("Urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni.
        /// </summary>
        public static string Yeni {
            get {
                return ResourceManager.GetString("Yeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Bildirimin Var.
        /// </summary>
        public static string YeniBildirim {
            get {
                return ResourceManager.GetString("YeniBildirim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Görev.
        /// </summary>
        public static string YeniGorev {
            get {
                return ResourceManager.GetString("YeniGorev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Mesajın Var.
        /// </summary>
        public static string YeniMesaj {
            get {
                return ResourceManager.GetString("YeniMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Takipçi.
        /// </summary>
        public static string YeniTakipci {
            get {
                return ResourceManager.GetString("YeniTakipci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Yorum.
        /// </summary>
        public static string YeniYorum {
            get {
                return ResourceManager.GetString("YeniYorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıllık.
        /// </summary>
        public static string Yillik {
            get {
                return ResourceManager.GetString("Yillik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici.
        /// </summary>
        public static string Yonetici {
            get {
                return ResourceManager.GetString("Yonetici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklenenler.
        /// </summary>
        public static string Yuklenen {
            get {
                return ResourceManager.GetString("Yuklenen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamanla.
        /// </summary>
        public static string Zamanla {
            get {
                return ResourceManager.GetString("Zamanla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaten Hesabın Var Mı? Giriş Yap.
        /// </summary>
        public static string ZatenHesap {
            get {
                return ResourceManager.GetString("ZatenHesap", resourceCulture);
            }
        }
    }
}
